### ISSUE TITLE
`Database access not available` at http://localhost:7474/

### ISSUE THREAD

**Issue by knok** [toposoid/toposoid#1]
I tried to use toposoid with the following step:
```
$ docker-compose up -d
$ curl -X POST -H "Content-Type: application/json" -d '{"knowledgeList":[{"sentence":"案ずるより産むが易し。", "json":"{}"}]}' http://localhost:9002/regist
"result":"OK"
```
Then, try to access http://localhost:7474/, then the output says `Database access not available`
![image](https://user-images.githubusercontent.com/1149984/137842910-cdb40589-4bf4-4c9d-bd86-17ecdb7b598d.png)
So I tried to access with user: `log4j`, password: `p@ssw0rd` but can't connect.

I just tried the following:
```
curl -X POST -H "Content-Type: application/json" -d '{"premise":[],"claim":["案ずるより産むが易し。"]}' http://localhost:9004/analyze
"{"records":[]}"
```
It seems not expected result.
How do I inspect the problem?

**Comment by makoto-kubodera** [comment]
Thank you for pointing out the issue.　@knok
Thank you for replying to the issue.　@fuji44 

> I don't know why I need to connect chyper-shell

I didn't expect this care.
If I find the cause, I will comment.

As a side note, I will comment on the additional information.

The meaning of localhost explained in the usage is an example assuming that the execution environment of curl and browser is the same as Docker's Host. If the access client to toposoid is different from Docker's Host, you can connect by modifying docker-compose.yml. Please read the following.

https://github.com/toposoid/toposoid#note
